### ISSUE TITLE
Check for fenced volumes

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#437]
The HC now reports fenced volumes also as halted, this ticket is to make a distinction between fenced and halted local volumes.

https://docs.google.com/document/d/1JLli7g1Abri8O5mJkbg6lAD5CG8QLBOL60I25B1hVtc/

**Comment by redlicha** [comment]
There's no difference between "fenced" and "halted" volumes: `halted` is a volume state that is entered after a non-recoverable error is encountered, and one of these is if a volume instance is fenced. The reason for entering the `halted` state is emitted as an event via AMQP / RabbitMQ so that is one indication. Another indication for fencing is if the volume is actually owned by another node / running there (the `ObjectRegistry` can provide that info).

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/439
Released in https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.4.8
