### ISSUE TITLE
Health check for alba creates too many namespaces and does not delete them

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/openvstorage-health-check#62]
On every node, for every volumedriver/proxy, for every preset a new namespace is created, an object is uploaded, downloaded and deleted, but the namespace is never deleted.

It would be nice to test every backend just once (instead of from all nodes) and clean up the namespace afterwards.

**Comment by kinvaris** [comment]
I think this should be still available:
`On every node, for every volumedriver/proxy, for every preset a new namespace is created, an object is uploaded, downloaded and deleted`

The namespace is indeed never deleted. This gives indeed some problems: you cannot delete the presets anymore because leftover namespaces are still available in the backend, garbage in the backend, ...

**Comment by wimpers** [comment]
I had a small discussion with @toolslive about this.

It doesn't make sense to create a namespace for each preset.  Not even creating new namespaces is 100% staunch as they might all end up on the same nsm_host. It doesn't test all the other nsm_hosts.

I'm not 100% sure how we would best tackle it but I agree with @jtorreke that testing each preset fro every backend on every node isn't very fruitfull. Testing each proxy seems good and maybe test the backend once?

**Comment by kinvaris** [comment]
@wimpers: it does not matter that it might end up on the same NSM_host. We are testing the NSM hosts with the arakoon test. With that test we are not aiming to test the NSMs but we test the work ability of the presets. 

It is important to test every preset that is or could be in use by a vpool at that moment. So maybe we can cut it down to that instead of testing all the presets that have been created on the cluster

**Comment by wimpers** [comment]
Had a talk with @kinvaris about this and I believe there is some confusion

- the health check creates a namespace per backend/preset combination (not per backend/preset/proxy) and reuses that namespace (no delete as deleted namespaces remain in the nsm_host). 
- it makes sense to test the preset for a backend to make sure that preset/backend combo can be used (objects can be written) at the time when the health check runs
- to test the proxy of a node it makes sense to test the full flow of uploading and deleting an object
- since the health check runs independent on each node (it doesn't know of a run on another node) we need to check all preset/backend combo's that proxy knows about. (Basically there is  no way to detect that preset/backend combo was tested by another node)
- the nsm_host gets tested through the arakoon tests

So I'm inclined to say 'won't fix' but open for suggestions and discussion.

**Comment by kinvaris** [comment]
We will discuss this again when @jtorreke returns from vacation how we could create an alternate solution if possible together with @toolslive & @domsj. 

What I would certainly discuss this:
The namespace is indeed never deleted. This gives indeed some problems: you cannot delete the presets anymore because leftover namespaces are still available in the backend, garbage in the backend, ...

**Comment by kinvaris** [comment]
Just discussed the part were we would delete the namespace instead of keeping it would have some dangers and he says it would not contain any dangers.

For example lets say we have 2 presets for a backend. Running the healthcheck 24 times a day for a whole year. We would create 175200 namespaces. For 10 years that is 1 752 000 namespaces for 10 year. 

We can maximum put 2^32 amount of namespaces on a cluster. That would be max. 4 294 967 296 namespaces.

**Comment by kinvaris** [comment]
closing this issue and continuing in #85
