### ISSUE TITLE
If 1 preset works the backend should be ok

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#82]
Validate: #81

**Comment by JeffreyDevloo** [comment]
## Test case 1
No presets
### Steps
- Setup latest cluster
- Added backend
- Removed default preset
- Ran healthcheck

### Output
```
[FAILED] Alba backend 'mybackend' is NOT available for vPool use, preset requirements NOT SATISFIED! There are 4 working disks AND 0 defective disks!
```

## Test case 2
Single unsatisfied preset
### Steps
- Setup latest cluster
- Added backend
- Removed default preset
- Ran healthcheck

### Output
```
[FAILED] Alba backend 'mybackend' is NOT available for vPool use, preset requirements NOT SATISFIED! There are 4 working disks AND 0 defective disks!
```

## Test case 3
Satisfied preset
### Steps
- Setup latest cluster
- Added backend
- Removed default preset
- Ran healthcheck

### Output
```
[SUCCESS] Alba backend 'mybackend' should be AVAILABLE FOR vPOOL USE, ALL disks are working fine!

```

### Test result
Test passed.

### Proposed enhancement
Log if no preset was found (due to the possibility of the default preset being removed in future updates)

### Packages
- openvstorage-health-check          3.1.2-rev.176.0a97c0e-1                                  amd64        Open vStorage HealthCheck
